---
assets:
  - assets/images/
dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
description: A new Flutter project.
dev_dependencies:
  dart_code_metrics:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
name: flutter_chat_ui
publish_to: none
version: 1.0.0+1
